# Generated by Django 4.2.1 on 2023-05-23 14:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=account.models.avatar_upload_handler),
        ),
    ]
